locale: "en-US"
title: &my_name "Alex Gonçalves"
masthead_title: "My Many Lives"
subtitle: "in a Few Words"
title_separator: "|"
name: *my_name
description: "My personal website—projects, news articles, computer code, and educational resources"
baseurl: ""
url: "https://alexgonca.github.io"
repository: "alexgonca/alexgonca.github.io"
atom_feed:
  hide: true

author:
  name     : *my_name
  bio      : "Understanding Social Dynamics Through Data-Driven Insights"
  location : "New York, NY"


# Build settings
remote_theme: "mmistakes/minimal-mistakes@18e89666a6ce34e393d82812664fa42bbb9752c7"
plugins:
  - jekyll-include-cache
